[package]
name = "diem"
version = "0.1.0"
authors = ["whytheplatypus <whytheplatypus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dirs = "2.0.2"
